config/routes.rb
MusicMap::Application.routes.draw do
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "log_out" => "sessions#destroy", :as => "log_out"

  resources :genres
  resources :artists
  resources :users
  resources :sessions

  match 'map' => 'maps#index'

  root :to => 'home#index'

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  attr_accessible :name, :artist_ids, :genre, :genre_id
  validates_presence_of :name
  validates_presence_of :genre
  
  has_many		:artist_related_artist_relationships, 
  				    :class_name 		=> "ArtistRelationship",
  				    :foreign_key		=> :related_artist_id

  has_many		:artists,
  				    :through			   => :artist_related_artist_relationships,
  				    :source				   => :artist

  has_many		:related_artist_artist_relationships,
  				    :class_name 		=>	"ArtistRelationship",
  				    :foreign_key		=> :artist_id

  has_many    :related_artists,
              :through        => :related_artist_artist_relationships,
              :source         => :related_artist

  belongs_to :genre
  belongs_to :user
end

app/models/artist_relationship.rb
class ArtistRelationship < ActiveRecord::Base
  attr_accessible :artist_id, :related_artist_id

  belongs_to :artist, :class_name => "Artist"
  belongs_to :related_artist, :class_name => "Artist"
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  attr_accessible :name

  has_many :artists
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :artists
  has_many :genres
  
  attr_accessible :email, :password, :password_confirmation
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  private 

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  # GET /artists
  # GET /artists.json
  def index
    if current_user
      @artists = current_user.artists
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @artists }
    end
  end
  def map
    @artists = Artist.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @artists }
    end
  end



  # GET /artists/new
  # GET /artists/new.json
  def new
    @artist = Artist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @artist }
    end
  end

  # GET /artists/1/edit
  def edit
    @artist = Artist.find(params[:id])
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = current_user.artists.create!(params[:artist])
   
    respond_to do |format|
      if @artist.save
        format.html { redirect_to "/artists" , notice: 'Artist was successfully created.' }
        format.json { render json: @artist, status: :created, location: @artist }
      else
        format.html { render action: "new" }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /artists/1
  # PUT /artists/1.json
  def update
    @artist = current_user.artists.find(params[:id])
    @artist.update_attributes!(params[:artist])
    respond_to do |format|
      if @artist.update_attributes(params[:artist])
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist = current_user.artists.find(params[:id])
    @artist.destroy

    respond_to do |format|
      format.html { redirect_to artists_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  # GET /genres
  # GET /genres.json
  def index
    if current_user
      @genres = current_user.genres
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @genres }
    end
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
    @genre = Genre.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @genre }
    end
  end

  # GET /genres/new
  # GET /genres/new.json
  def new
    @genre = Genre.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @genre }
    end
  end

  # GET /genres/1/edit
  def edit
    @genre = current_user.genres.find(params[:id])
    @genre.update_attributes!(params[:genre])
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = current_user.genres.create!(params[:genre])

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render json: @genre, status: :created, location: @genre }
      else
        format.html { render action: "new" }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /genres/1
  # PUT /genres/1.json
  def update
    @genre = Genre.find(params[:id])

    respond_to do |format|
      if @genre.update_attributes(params[:genre])
        format.html { redirect_to @genre, notice: 'Genre was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre = current_user.genres.find(params[:id])
    @genre.destroy

    respond_to do |format|
      format.html { redirect_to genres_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 def index
 end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
  	@artists = current_user.artists
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @artist }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.authenticate(params[:email], params[:password])
  	if user
  		session[:user_id] = user.id
  		redirect_to root_url, :notice => "Logged in!"
  	else
  		 redirect_to "/log_in", notice: 'Your email or password was incorrect.'
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_url, :notice => "Logged Out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(params[:user])
  	if @user.save
  		redirect_to root_url, :notice => "Signed up!"
  	else
  		render "new"
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :genre %><br />
    <%= f.collection_select(:genre_id, Genre.all, :id, :name, {:include_blank => true, :default => '-'})%>
  </div>


  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

    Related Artists:
  <% for artist in current_user.artists %>
<div>
  <%= check_box_tag "artist[artist_ids][]", artist.id, @artist.artists.include?(artist) %>
  <%= artist.name %>
</div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<div class="background">
	<h1>Editing artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>
</div>

app/views/artists/index.html.erb
  <div class="grid_16">
  <h1>Artists</h1>

  <table id="artists_table" class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Genre</th>
    <th>Related Artists</th>

  </tr>

<% @artists.each do |artist| %>
  <tr>
    <td><%= artist.name %></td>
    <td><%= artist.genre.name %></td>
    <td><% unless artist.related_artists.empty? %>
      <ul class="inline">
        <% artist.related_artists.each.with_index do |rel, index| %>
          <% if index < 4 %>
          <li><%= rel.name %></li>
          <% end %>
        <% end %>
      </ul>
    <% end %>
  </td>
    <td><%= link_to 'Show', artist %></td>
    <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
    <td><%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Artist', new_artist_path %>

    
  </div>

app/views/artists/new.html.erb
<h1>New artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/genres/_form.html.erb
<%= form_for(@genre) do |f| %>
  <% if @genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
      <% @genre.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/genres/edit.html.erb
<h1>Editing genre</h1>

<%= render 'form' %>

<%= link_to 'Show', @genre %> |
<%= link_to 'Back', genres_path %>

app/views/genres/index.html.erb
<h1>Listing genres</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @genres.each do |genre| %>
  <tr>
    <td><%= genre.name %></td>
    <td><%= link_to 'Show', genre %></td>
    <td><%= link_to 'Edit', edit_genre_path(genre) %></td>
    <td><%= link_to 'Destroy', genre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Genre', new_genre_path %>

app/views/genres/new.html.erb
<h1>New genre</h1>

<%= render 'form' %>

<%= link_to 'Back', genres_path %>

app/views/genres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @genre.name %>
</p>


<%= link_to 'Edit', edit_genre_path(@genre) %> |
<%= link_to 'Back', genres_path %>

app/views/home/index.html.erb
<link rel="stylesheet" href="/assets/home.css">

<div class="home">
	<div id="welcome">
		<img src="/assets/logo_big.png" alt="" width="300px">
	</div>

	<div id="home_links">
		<ul>
			<li><a href="/log_in" id="login">LOGIN</a></li>
			<li></li>
			<li><a href="#" id="try">TRY IT OUT</a></li>
		</ul>		
	</div>

	<div class="sign_up">
		<h1>- OR -</h1>
		<a href="/sign_up">CLICK HERE TO SIGN UP</a>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicMap</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "960" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "d3" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="user_nav">
	<% if current_user %>
		Logged in as <%= current_user.email %>.
		<%= link_to "Log Out", log_out_path %>
	<% else %>
		<%= link_to "Sign up", sign_up_path %> or
		<%= link_to "Log in", log_in_path %>
	<% end %>
	
</div>

<div class="container_16">
	
	<%= yield %>
</div>


</body>
</html>

app/views/users/new.html.erb
<link rel="stylesheet" href="/assets/users.css">

<div class="sign_up">
	<h1>Sign Up</h1>
</div>

<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div class="error_messages">
			<h2>Form is invalid</h2>
			<ul>
				<% for message in @user.errors.full_messages %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>

<% end %>	

	<div class="fields">

	<p>
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</p>
	<p>
		<%= f.label :password %><br />
		<%= f.password_field :password %>
	</p>
	<p>
		<%= f.label :password_confirmation %><br />
		<%= f.password_field :password_confirmation %>
	</p>
	</div>
	
	</p>
	<p class="button"><%= f.submit %></p>
<% end %>